server:
  port: 8081

#  spring:
#    kafka:
#      bootstrap-servers: localhost:9092
#      consumer:
#        group-id: my-group-id
spring:
  datasource:
    url: jdbc:mysql://3.134.88.111:3306/test
    username: bilvantis
    password: AgRi@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        envers:
          autoRegisterListeners: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        ddl-auto: update
    hibernate:
      ddl-auto: update



#camel:
#  component:
#    kafka:
#      brokers: localhost:9092
